# Generated by Django 5.0.1 on 2024-02-26 14:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pet_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstoreapp.cart')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstoreapp.pet')),
            ],
        ),
    ]
